# -*- coding: utf-8 -*-
"""TrainSpyderV1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tBkL-uy6ZLnaBX3zVCVSQH28jFGY-2EJ

## Import libraries
"""


import os
import numpy as np
import math
import matplotlib.pyplot as plt

import time
from tqdm import tqdm

import torchvision.transforms as transforms
from torchvision.utils import save_image

from torch.utils.data import DataLoader
from torchvision import datasets
from torch.autograd import Variable

import torch.nn as nn
import torch.nn.functional as F
import torch

from datasets import load_dataset
from dataclasses import dataclass

os.makedirs("images", exist_ok=True)

"""## Configure Training Parameters"""

import argparse
import pickle

# Crear la carpeta si no existe
os.makedirs("LOSSES", exist_ok=True)
os.makedirs("MODELS", exist_ok=True)
os.makedirs("ACCURACY", exist_ok=True)

# Verificar cuántas GPUs tienes disponibles
num_gpus = torch.cuda.device_count()
print(f"Número de GPUs disponibles: {num_gpus}")

# Elegir la GPU (el índice empieza en 0, así que la primera GPU es 0 y la segunda es 1)
gpu_to_use = 1  # Cambia este valor a 0 o 1 según la GPU que desees usar

if gpu_to_use < num_gpus:
    torch.cuda.set_device(gpu_to_use)
    print(f"Usando GPU {gpu_to_use}: {torch.cuda.get_device_name(gpu_to_use)}")
else:
    print("Índice de GPU no válido, usando la GPU 0 por defecto")
    torch.cuda.set_device(0)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--n_epochs', type=int, default=1000, help='number of epochs of training')
    parser.add_argument('--batch_size', type=int, default=128, help='size of the batches')
    parser.add_argument('--lr', type=float, default=0.0001, help='adam: learning rate')
    parser.add_argument('--b1', type=float, default=0.5, help='adam: decay of first order momentum of gradient')
    parser.add_argument('--b2', type=float, default=0.9, help='adam: decay of second order momentum of gradient')
    parser.add_argument('--n_cpu', type=int, default=24, help='number of cpu threads to use during batch generation')
    parser.add_argument('--latent_dim', type=int, default=256, help='dimensionality of the latent space')
    parser.add_argument('--code_dim', type=int, default=10, help='dimensionality of the code space')
    parser.add_argument('--n_classes', type=int, default=1, help='number of classes for dataset')
    parser.add_argument('--img_size', type=int, default=128, help='size of each image dimension')
    parser.add_argument('--channels', type=int, default=1, help='number of image channels')
    parser.add_argument('--sample_interval', type=int, default=500, help='interval between image sampling')
    opt = parser.parse_args([])  # Pass an empty list to bypass the command-line arguments



    # Save the opt variable to a file
    with open('opt.pkl', 'wb') as f:
        pickle.dump(opt, f)

    print(opt)

if __name__ == '__main__':
    main()

# Function to load the saved opt variable
def load_opt():
    with open('opt.pkl', 'rb') as f:
        return pickle.load(f)

# Load and print the opt variable
opt = load_opt()
print(opt)

cuda = True if torch.cuda.is_available() else False
print(cuda)

def weights_init_normal(m):
    classname = m.__class__.__name__
    if classname.find("Conv") != -1:
        torch.nn.init.normal_(m.weight.data, 0.0, 0.02)
    elif classname.find("BatchNorm2d") != -1:
        torch.nn.init.normal_(m.weight.data, 1.0, 0.02)
        torch.nn.init.constant_(m.bias.data, 0.0)

"""## Generator"""

def weights_init_normal(m):
    classname = m.__class__.__name__
    if classname.find("Conv") != -1:
        torch.nn.init.normal_(m.weight.data, 0.0, 0.02)
    elif classname.find("BatchNorm2d") != -1:
        torch.nn.init.normal_(m.weight.data, 1.0, 0.02)
        torch.nn.init.constant_(m.bias.data, 0.0)


class Generator(nn.Module):
    def __init__(self):
        super(Generator, self).__init__()

        self.init_size = opt.img_size // 4
        self.l1 = nn.Sequential(nn.Linear(opt.latent_dim, 128 * self.init_size ** 2))

        self.conv_blocks = nn.Sequential(
            nn.BatchNorm2d(128),
            nn.Upsample(scale_factor=2),
            nn.Conv2d(128, 128, 3, stride=1, padding=1),
            nn.BatchNorm2d(128, 0.8),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Upsample(scale_factor=2),
            nn.Conv2d(128, 64, 3, stride=1, padding=1),
            nn.BatchNorm2d(64, 0.8),
            nn.LeakyReLU(0.2, inplace=True),
            nn.Conv2d(64, opt.channels, 3, stride=1, padding=1),
            nn.Tanh(),
        )

    def forward(self, z):
        out = self.l1(z)
        out = out.view(out.shape[0], 128, self.init_size, self.init_size)
        img = self.conv_blocks(out)
        return img

"""## Dicriminator"""

class Discriminator(nn.Module):
    def __init__(self):
        super(Discriminator, self).__init__()

        def discriminator_block(in_filters, out_filters, bn=True):
            block = [nn.Conv2d(in_filters, out_filters, 3, 2, 1), nn.LeakyReLU(0.2, inplace=True), nn.Dropout2d(0.25)]
            if bn:
                block.append(nn.BatchNorm2d(out_filters, 0.8))
            return block

        self.model = nn.Sequential(
            *discriminator_block(opt.channels, 16, bn=False),
            *discriminator_block(16, 32),
            *discriminator_block(32, 64),
            *discriminator_block(64, 128),
        )

        # The height and width of downsampled image
        ds_size = opt.img_size // 2 ** 4
        self.adv_layer = nn.Sequential(nn.Linear(128 * ds_size ** 2, 1), nn.Sigmoid())

    def forward(self, img):
        out = self.model(img)
        out = out.view(out.shape[0], -1)
        validity = self.adv_layer(out)

        return validity

"""## Configure training data"""

# Loss function
adversarial_loss = torch.nn.BCELoss()

# Initialize generator and discriminator
generator = Generator()
discriminator = Discriminator()

if cuda:
    generator.cuda()
    discriminator.cuda()
    adversarial_loss.cuda()

# Initialize weights
generator.apply(weights_init_normal)
discriminator.apply(weights_init_normal)



### Define the transformations

transform = transforms.Compose([
    transforms.Grayscale(opt.channels),  # Convert to 3 channels if needed
    transforms.Resize((opt.img_size, opt.img_size)),  # Ensure opt.img_size is an integer or a tuple (height, width)
    transforms.ToTensor(),
])



# # Load the dataset
# dataset = datasets.ImageFolder(root=data_path, transform=transform)

# # Create the DataLoader
# dataloader = torch.utils.data.DataLoader(dataset, batch_size=opt.batch_size, shuffle=True)

@dataclass
class BaseConfig:
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    DATASET = "GLIOMA_TUMOR"  # Cambiado para reflejar el nuevo dataset
    DATASET_PATH = "IngenieroMor/BRAINS_GLIOMA_TUMOR"  # Actualiza con la ruta de tu dataset en Hugging Face

    # For logging inference images and saving checkpoints.
    root_log_dir = os.path.join("Logs_Checkpoints", "Inference")
    root_checkpoint_dir = os.path.join("Logs_Checkpoints", "checkpoints")

    # Current log and checkpoint directory.
    log_dir = "version_0"
    checkpoint_dir = "version_0"

config = BaseConfig()

# Load the dataset from Hugging Face
dataset = load_dataset(config.DATASET_PATH, split='train')

# Define a custom dataset class to apply transformations
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self, dataset, transform=None):
        self.dataset = dataset
        self.transform = transform

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        image = self.dataset[idx]['image']
        label = self.dataset[idx]['label']
        if self.transform:
            image = self.transform(image)
        return image, label

# Create the custom dataset
custom_dataset = CustomDataset(dataset, transform=transform)

# Create the DataLoader
dataloader = DataLoader(custom_dataset, batch_size=opt.batch_size, shuffle=True)

"""## Optimizers"""

# Optimizers
optimizer_G = torch.optim.Adam(generator.parameters(), lr=opt.lr, betas=(opt.b1, opt.b2))
optimizer_D = torch.optim.Adam(discriminator.parameters(), lr=opt.lr, betas=(opt.b1, opt.b2))

Tensor = torch.cuda.FloatTensor if cuda else torch.FloatTensor

def save_model(epoch, generator, discriminator, path='models/'):
    # Crea el directorio si no existe
    if not os.path.exists(path):
        os.makedirs(path)
    
    # Guarda el estado del generador y el discriminador en archivos
    torch.save({
        'epoch': epoch,
        'generator_state_dict': generator.state_dict(),
        'discriminator_state_dict': discriminator.state_dict(),
    }, os.path.join(path, f'model_epoch_{epoch}.pth'))
    print(f"Models saved at epoch {epoch}")


"""## Training"""

# Commented out IPython magic to ensure Python compatibility.


# Initialize lists to store losses and accuracies
g_losses = []
d_losses = []
d_accuracies = []

for epoch in range(opt.n_epochs):
    start_time = time.time()  # Start timer for the epoch

    # Use tqdm for the progress bar
    for i, (imgs, _) in enumerate(tqdm(dataloader, desc=f"Epoch {epoch + 1}/{opt.n_epochs}", unit="batch")):

        # Adversarial ground truths
        valid = Variable(Tensor(imgs.shape[0], 1).fill_(1.0), requires_grad=False)
        fake = Variable(Tensor(imgs.shape[0], 1).fill_(0.0), requires_grad=False)

        # Configure input
        real_imgs = Variable(imgs.type(Tensor))

        # -----------------
        #  Train Generator
        # -----------------

        optimizer_G.zero_grad()

        # Sample noise as generator input
        z = Variable(Tensor(np.random.normal(0, 1, (imgs.shape[0], opt.latent_dim))))

        # Generate a batch of images
        gen_imgs = generator(z)

        # Loss measures generator's ability to fool the discriminator
        g_loss = adversarial_loss(discriminator(gen_imgs), valid)

        g_loss.backward()
        optimizer_G.step()

        # ---------------------
        #  Train Discriminator
        # ---------------------

        optimizer_D.zero_grad()

        # Measure discriminator's ability to classify real from generated samples
        real_loss = adversarial_loss(discriminator(real_imgs), valid)
        fake_loss = adversarial_loss(discriminator(gen_imgs.detach()), fake)
        d_loss = (real_loss + fake_loss) / 2

        d_loss.backward()
        optimizer_D.step()

        # Save losses for this batch
        g_losses.append(g_loss.item())
        d_losses.append(d_loss.item())

        # Calculate discriminator accuracy
        real_preds = discriminator(real_imgs)
        fake_preds = discriminator(gen_imgs.detach())

        real_accuracy = torch.mean((real_preds > 0.5).float()).item()
        fake_accuracy = torch.mean((fake_preds < 0.5).float()).item()
        d_accuracy = (real_accuracy + fake_accuracy) / 2

        d_accuracies.append(d_accuracy)

        print(
            "[Epoch %d/%d] [D loss: %f] [G loss: %f] [D accuracy: %f]"      % (epoch, opt.n_epochs, d_loss.item(), g_loss.item(), d_accuracy)
        )

        batches_done = epoch * len(dataloader) + i
        if batches_done % opt.sample_interval == 0:
            save_image(gen_imgs.data[:25], "images/%d.png" % batches_done, nrow=5, normalize=True)

    end_time = time.time()  # End timer for the epoch
    epoch_duration = end_time - start_time
    print(f"Epoch {epoch + 1} completed in {epoch_duration:.2f} seconds")
    
    
    # Save the model every 100 epochs
    if (epoch + 1) % 100 == 0:
        # Crear la carpeta si no existe
        os.makedirs("LOSSES", exist_ok=True)
        os.makedirs("ACCURACY", exist_ok=True)
        save_model(epoch + 1, generator, discriminator)
        # Plot losses and accuracy after each epoch
        plt.figure(figsize=(15, 5))

        # Losses plot
        plt.subplot(1, 2, 1)
        plt.plot(g_losses, label="Generator Loss")
        plt.plot(d_losses, label="Discriminator Loss")
        plt.xlabel("Batch")
        plt.ylabel("Loss")
        plt.legend()
        plt.grid(True)
        plt.title(f"Epoch {epoch + 1} Losses")
        plt.savefig(os.path.join('LOSSES', f"Epoch {epoch + 1} Losses.png"))
        plt.close()

        # Accuracy plot
        plt.subplot(1, 2, 2)
        plt.plot(d_accuracies, label="Discriminator Accuracy", color='orange')
        plt.xlabel("Batch")
        plt.ylabel("Accuracy")
        plt.legend()
        plt.grid(True)
        plt.title(f"Epoch {epoch + 1} Discriminator Accuracy")
        plt.savefig(os.path.join('ACCURACY', f"Epoch {epoch + 1} accuracy.png"))
        plt.close()

# Save the final loss and accuracy plot
plt.figure(figsize=(15, 5))

# Losses plot
plt.subplot(1, 2, 1)
plt.plot(g_losses, label="Generator Loss")
plt.plot(d_losses, label="Discriminator Loss")
plt.xlabel("Batch")
plt.ylabel("Loss")
plt.legend()
plt.grid(True)
plt.title("Final Losses")

# Accuracy plot
plt.subplot(1, 2, 2)
plt.plot(d_accuracies, label="Discriminator Accuracy", color='orange')
plt.xlabel("Batch")
plt.ylabel("Accuracy")
plt.legend()
plt.grid(True)
plt.title("Final Discriminator Accuracy")

plt.savefig("final_losses_and_accuracy.png")
plt.close()

"""## Export model"""

# Guarda el estado del modelo del generador en un archivo
torch.save({
    'generator_state_dict': generator.state_dict(),
}, 'generator_model.pth')

print("Modelo del generador guardado en 'generator_model.pth'")

